{ inputs, config, pkgs, pkgs-unstable, ... }:

{
  environment.systemPackages = ( with pkgs; [
    vulkan-tools
    glxinfo
    git
    iperf
    wget
    pciutils
    inetutils
    remmina
    vlc
    mpv
    sl
    htop
    btop-rocm
    glances
    fastfetch
    gamemode
    winetricks
    android-tools
    gamescope
    pokemmo-installer
    vivaldi-overlayed
    vivaldi-ffmpeg-codecs
    prism-overlayed    
    lutris-overlayed
    hfsprogs
    krita
    inkscape
    heroic
    bs-manager
    sops
    rage
    ssh-to-age
    osu-lazer-bin
    whatsapp-for-linux
    nheko
    blender
    qbittorrent
    scrcpy
    go
    gcc
    telegram-desktop
    nix-output-monitor
    age
    qrencode
    libreoffice
    foliate
  ]) ++ ( with pkgs-unstable; [
    wineWowPackages.stagingFull
    ryubing
    cemu
    vesktop
    firefox
  ]);
}